spring:
  profiles:
    active: dev

---

spring:
  profiles: dev
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://${MSSQL_ADDR:172.28.128.31}:${MSSQL_PORT:1433};databasename=${MSSQL_DB:master}

server:
  port: ${NOMAD_HOST_PORT_http:8080}